<?php use App\Core\Html as H; use App\Core\Money; ?>
<div class="page-heading"><div><p class="eyebrow">ENTENDA SEUS HÁBITOS</p><h1>Análises</h1><p class="text-secondary">Explore seu consumo por período. Transferências e pagamentos de fatura ficam fora dos gastos.</p></div></div>
<form method="get" class="card mb-4"><div class="card-body row g-3">
<div class="col-md-3"><label for="analysis-start" class="form-label">Início (competência)</label><input id="analysis-start" type="date" name="inicio" class="form-control" value="<?= H::escape($start) ?>" required></div><div class="col-md-3"><label for="analysis-end" class="form-label">Fim</label><input id="analysis-end" type="date" name="fim" class="form-control" value="<?= H::escape($end) ?>" required></div>
<div class="col-md-3"><label for="analysis-group" class="form-label">Agrupar por</label><select id="analysis-group" name="agrupar" class="form-select"><?php foreach(['categoria'=>'Categoria','subcategoria'=>'Subcategoria','conta'=>'Conta','cartao'=>'Cartão','meio'=>'Meio de pagamento','origem'=>'Recorrente / eventual','mes'=>'Mês'] as $key=>$name): ?><option value="<?= $key ?>" <?= $dimension===$key ? 'selected' : '' ?>><?= $name ?></option><?php endforeach; ?></select></div>
<div class="col-md-3"><label for="analysis-account" class="form-label">Conta</label><select id="analysis-account" name="conta_id" class="form-select"><option value="">Todas</option><?php foreach($accounts as $a): ?><option value="<?= (int)$a['id'] ?>" <?= (int)($filters['conta_id'] ?? 0)===(int)$a['id'] ? 'selected' : '' ?>><?= H::escape($a['nome']) ?></option><?php endforeach; ?></select></div>
<div class="col-md-3"><label for="analysis-card" class="form-label">Cartão</label><select id="analysis-card" name="cartao_id" class="form-select"><option value="">Todos</option><?php foreach($cards as $c): ?><option value="<?= (int)$c['id'] ?>" <?= (int)($filters['cartao_id'] ?? 0)===(int)$c['id'] ? 'selected' : '' ?>><?= H::escape($c['nome']) ?></option><?php endforeach; ?></select></div>
<div class="col-md-3"><label for="analysis-category" class="form-label">Subcategoria</label><select id="analysis-category" name="subgrupo_id" class="form-select"><option value="">Todas</option><?php foreach($categories as $c): ?><option value="<?= (int)$c['id'] ?>" <?= (int)($filters['subgrupo_id'] ?? 0)===(int)$c['id'] ? 'selected' : '' ?>><?= H::escape($c['grupo_nome'].' · '.$c['nome']) ?></option><?php endforeach; ?></select></div>
<div class="col-md-3"><label for="analysis-type" class="form-label">Tipo</label><select id="analysis-type" name="tipo" class="form-select"><option value="">Receitas e despesas</option><?php foreach(['receita'=>'Receitas','despesa'=>'Despesas'] as $k=>$n): ?><option value="<?= $k ?>" <?= ($filters['tipo'] ?? '')===$k ? 'selected' : '' ?>><?= $n ?></option><?php endforeach; ?></select></div>
<div class="col-md-3 d-flex align-items-end"><button class="btn btn-uai-primary w-100">Aplicar filtros</button></div>
</div></form>
<div class="row g-3 mb-4"><?php foreach(['receitas'=>'Receitas realizadas','despesas'=>'Despesas realizadas','resultado'=>'Resultado do período'] as $k=>$n): ?><div class="col-md-4"><div class="card metric-card"><div class="card-body"><p><?= $n ?></p><strong class="metric-value"><?= Money::format($k==='resultado' ? (int)$totals['receitas']-(int)$totals['despesas'] : (int)$totals[$k]) ?></strong></div></div></div><?php endforeach; ?></div>
<div class="row g-4"><div class="col-xl-8"><section class="card"><div class="card-body"><h2 class="h4">Distribuição do período</h2><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Descrição</th><th class="text-end">Receitas</th><th class="text-end">Despesas</th><th>Participação nas despesas</th></tr></thead><tbody><?php foreach($rows as $row): $percent=(int)$totals['despesas']>0 ? max(0,round((int)$row['despesas']/(int)$totals['despesas']*100)) : 0; ?><tr><td><?= H::escape($row['nome']) ?></td><td class="text-end"><?= Money::format((int)$row['receitas']) ?></td><td class="text-end"><?= Money::format((int)$row['despesas']) ?></td><td><progress class="uai-progress" max="100" value="<?= min(100,$percent) ?>" aria-label="Participação de <?= H::escape($row['nome']) ?>"></progress><small><?= $percent ?>%</small></td></tr><?php endforeach; ?><?php if (!$rows): ?><tr><td colspan="4" class="text-secondary py-4">Nenhum lançamento realizado nesse período e filtro.</td></tr><?php endif; ?></tbody></table></div></div></section></div><div class="col-xl-4"><section class="card mb-4"><div class="card-body"><h2 class="h4">Maiores despesas</h2><?php foreach($top as $t): ?><a class="list-row text-decoration-none" href="<?= H::escape($basePath.'/movimentacoes/'.$t['transacao_id']) ?>"><span><?= H::escape($t['descricao']) ?></span><strong><?= Money::format((int)$t['valor']) ?></strong></a><?php endforeach; ?><?php if (!$top): ?><p class="text-secondary">Sem despesas no período.</p><?php endif; ?></div></section><section class="card"><div class="card-body"><h2 class="h4">Comparação mensal</h2><p class="small text-secondary"><?= H::escape($month) ?> em relação ao mês anterior, com os mesmos filtros de conta e categoria.</p><p>Diferença nas despesas: <strong><?= Money::format((int)$current['despesas']-(int)$previous['despesas']) ?></strong></p><p class="small text-secondary mb-0">Média mensal do período selecionado: <?= Money::format((int)round((int)$totals['despesas']/max(1,((int)substr($end,0,4)-(int)substr($start,0,4))*12+(int)substr($end,5,2)-(int)substr($start,5,2)+1))) ?></p></div></section></div></div>
