<?php use App\Core\Html as H; use App\Core\Money; ?>
<div class="page-heading"><div><p class="eyebrow">SEU DINHEIRO, COM CLAREZA</p><h1>Visão geral</h1><p class="text-secondary">Olá, <?= H::escape(explode(' ',$usuario['nome'])[0]) ?>. Acompanhe o presente e organize o próximo passo.</p></div><form method="get" class="d-flex gap-2"><label class="visually-hidden" for="dash-month">Mês dos resultados</label><input id="dash-month" class="form-control" type="month" name="mes" value="<?= H::escape($month) ?>" required><button class="btn btn-outline-secondary">Ver</button></form></div>
<?php if (!$accounts || !$categories): ?><div class="welcome-strip mb-4"><div><h2 class="h5 mb-1">Vamos organizar seu começo?</h2><span>Cadastre uma conta, personalize suas categorias e registre o primeiro lançamento.</span></div><a class="btn btn-uai-primary" href="<?= H::escape($basePath.'/comecar') ?>">Primeiros passos →</a></div><?php endif; ?>
<div class="row g-3 mb-4"><div class="col-md-6 col-xl-3"><article class="card metric-card featured"><div class="card-body"><p>Saldo nas contas hoje</p><strong class="metric-value"><?= Money::format((int)$balance) ?></strong><small>Contas ativas · valores confirmados</small></div></article></div><div class="col-md-6 col-xl-3"><article class="card metric-card"><div class="card-body"><p>Previsão até <?= date('t/m') ?></p><strong class="metric-value"><?= Money::format((int)$projection) ?></strong><small>Saldo + pendências − faturas a pagar</small></div></article></div><div class="col-md-6 col-xl-3"><article class="card metric-card"><div class="card-body"><p>Receitas · <?= H::escape($month) ?></p><strong class="metric-value text-success"><?= Money::format((int)$totals['receitas']) ?></strong><small>Por competência · realizadas</small></div></article></div><div class="col-md-6 col-xl-3"><article class="card metric-card"><div class="card-body"><p>Despesas · <?= H::escape($month) ?></p><strong class="metric-value"><?= Money::format((int)$totals['despesas']) ?></strong><small>Consumo, líquido de estornos</small></div></article></div></div>
<p class="small text-secondary mb-4">A previsão usa apenas compromissos cadastrados, incluindo atrasados. Recorrências ainda não processadas não entram nessa estimativa.</p>
<div class="row g-4"><div class="col-xl-8"><section class="card mb-4"><div class="card-body"><div class="section-heading"><h2 class="h4">Receitas e despesas</h2><a href="<?= H::escape($basePath.'/analises?mes='.$month) ?>">Explorar análises →</a></div><p class="small text-secondary">Últimos seis meses · por competência</p>
<?php $map=array_column($series,null,'nome'); $maxValue=max([1,...array_map(fn($r)=>max((int)$r['receitas'],(int)$r['despesas']),$series)]); ?>
<div class="chart-legend"><span class="legend-income">Receitas</span><span class="legend-expense">Despesas</span></div>
<div class="month-chart" role="img" aria-label="Comparação mensal de receitas e despesas; valores na tabela abaixo">
<?php for($i=-5;$i<=0;$i++): $m=\App\Core\FinancialDate::shift($month,$i); $row=$map[$m] ?? ['receitas'=>0,'despesas'=>0]; ?><div class="chart-month"><div class="chart-columns"><div class="chart-bar income" style="height:<?= max(2,round(max(0,(int)$row['receitas'])/$maxValue*100)) ?>%" title="Receitas: <?= Money::format((int)$row['receitas']) ?>"></div><div class="chart-bar expense" style="height:<?= max(2,round(max(0,(int)$row['despesas'])/$maxValue*100)) ?>%" title="Despesas: <?= Money::format((int)$row['despesas']) ?>"></div></div><span><?= H::escape(substr($m,5,2).'/'.substr($m,2,2)) ?></span></div><?php endfor; ?></div>
<details class="mt-3"><summary>Ver valores do gráfico</summary><div class="table-responsive"><table class="table"><thead><tr><th>Mês</th><th>Receitas</th><th>Despesas</th><th>Resultado</th></tr></thead><tbody><?php foreach($series as $s): ?><tr><td><?= H::escape($s['nome']) ?></td><td><?= Money::format((int)$s['receitas']) ?></td><td><?= Money::format((int)$s['despesas']) ?></td><td><?= Money::format((int)$s['receitas']-(int)$s['despesas']) ?></td></tr><?php endforeach; ?></tbody></table></div></details>
</div></section><section class="card"><div class="card-body"><div class="section-heading"><h2 class="h4">Próximos compromissos</h2><a href="<?= H::escape($basePath.'/recorrencias') ?>">Recorrências →</a></div><?php if (!$upcoming): ?><p class="empty-state">Nenhuma pendência cadastrada. Seus próximos vencimentos aparecerão aqui.</p><?php endif; ?><?php foreach($upcoming as $t): ?><a class="list-row text-decoration-none" href="<?= H::escape($basePath.'/movimentacoes/'.$t['id']) ?>"><div><?= H::escape($t['descricao']) ?><small class="d-block <?= $t['data_vencimento']<date('Y-m-d') ? 'text-danger' : 'text-secondary' ?>"><?= H::date($t['data_vencimento']) ?> · <?= $t['data_vencimento']<date('Y-m-d') ? 'Atrasado' : ($t['tipo']==='receita' ? 'A receber' : 'A pagar') ?></small></div><strong><?= Money::format((int)$t['valor_centavos']) ?></strong></a><?php endforeach; ?></div></section></div>
<div class="col-xl-4"><section class="card mb-4"><div class="card-body"><div class="section-heading"><h2 class="h4">Seus cartões</h2><a href="<?= H::escape($basePath.'/cartoes') ?>">Ver todos</a></div><?php $unpaid=array_values(array_filter($invoices,fn($f)=>(int)$f['total']>(int)$f['pago'])); usort($unpaid,fn($a,$b)=>strcmp($a['data_vencimento'],$b['data_vencimento'])); ?><?php if (!$unpaid): ?><p class="text-secondary py-3">Nenhuma fatura a pagar.</p><?php endif; ?><?php foreach(array_slice($unpaid,0,4) as $f): ?><a class="list-row text-decoration-none" href="<?= H::escape($basePath.'/faturas/'.$f['id']) ?>"><div><?= H::escape($f['cartao_nome']) ?><small class="d-block text-secondary">Vence <?= H::date($f['data_vencimento']) ?></small></div><strong><?= Money::format((int)$f['total']-(int)$f['pago']) ?></strong></a><?php endforeach; ?></div></section>
<section class="card mb-4"><div class="card-body"><div class="section-heading"><h2 class="h4">Orçamento do mês</h2><a href="<?= H::escape($basePath.'/planejamento?mes='.$month) ?>">Planejar</a></div><?php if (!$budgets): ?><p class="text-secondary py-3">Defina seus primeiros limites por categoria.</p><?php endif; ?><?php foreach(array_slice($budgets,0,4) as $b): ?><div class="py-3"><div class="d-flex justify-content-between small mb-2"><strong><?= H::escape($b['nome']) ?></strong><span><?= round((int)$b['realizado']/(int)$b['valor_limite_centavos']*100) ?>%</span></div><progress class="uai-progress" max="<?= (int)$b['valor_limite_centavos'] ?>" value="<?= min(max(0,(int)$b['realizado']),(int)$b['valor_limite_centavos']) ?>" aria-label="Consumo de <?= H::escape($b['nome']) ?>"></progress><small class="text-secondary">Restante: <?= Money::format((int)$b['valor_limite_centavos']-(int)$b['realizado']) ?></small></div><?php endforeach; ?></div></section>
<section class="card"><div class="card-body"><h2 class="h4">Resultado do mês</h2><strong class="metric-value"><?= Money::format((int)$totals['receitas']-(int)$totals['despesas']) ?></strong><p class="small text-secondary mt-2 mb-0">Pendentes: <?= Money::format((int)$totals['receber']) ?> a receber e <?= Money::format((int)$totals['pagar']) ?> a pagar, por competência.</p></div></section></div></div>
