<?php use App\Core\Html as H; use App\Core\Money; $groups=[]; foreach($categories as $c) if($c['tipo']==='despesa') $groups[$c['grupo_id']]=$c['grupo_nome']; ?>
<div class="page-heading"><div><p class="eyebrow">SEU PLANO PARA O MÊS</p><h1>Planejamento</h1><p class="text-secondary">Dê espaço ao que importa. Acompanhe seus limites por categoria.</p></div><form method="get" class="d-flex gap-2"><label class="visually-hidden" for="plan-month">Mês</label><input id="plan-month" name="mes" type="month" class="form-control" value="<?= H::escape($month) ?>" required><button class="btn btn-outline-secondary">Ver</button></form></div>
<div class="row g-4"><div class="col-xl-8">
<?php foreach ($budgets as $b): $limit=(int)$b['valor_limite_centavos']; $used=(int)$b['realizado']; $percent=max(0,round($used/$limit*100)); $tone=$used>$limit ? 'danger' : ($percent>=80 ? 'warning' : 'success'); ?>
<article class="card mb-3"><div class="card-body"><div class="d-flex justify-content-between gap-3"><h2 class="h5"><?= H::escape($b['nome']) ?></h2><span class="badge text-bg-<?= $tone ?>"><?= $used>$limit ? 'Excedido' : ($percent>=80 ? 'Atenção' : 'Dentro do limite') ?></span></div><p class="mb-2"><strong><?= Money::format($used) ?></strong> <span class="text-secondary">de <?= Money::format($limit) ?> · <?= $percent ?>%</span></p><progress class="uai-progress <?= $tone ?>" value="<?= min(max(0,$used),$limit) ?>" max="<?= $limit ?>" aria-label="Consumo de <?= H::escape($b['nome']) ?>"></progress><div class="d-flex justify-content-between mt-2 gap-2 flex-wrap"><span class="small">Restante: <?= Money::format($limit-$used) ?></span><span class="small text-secondary">Pendente: <?= Money::format((int)$b['pendente']) ?></span></div><details class="mt-3"><summary>Ajustar limite</summary><form class="row g-2 mt-2" method="post" action="<?= H::escape($basePath . '/planejamento') ?>">
    <?= H::fields($csrfToken) ?>
    <input type="hidden" name="mes" value="<?= H::escape($month) ?>">
    <input type="hidden" name="grupo_id" value="<?= (int) $b['grupo_id'] ?>">
    <div class="col-sm-8"><label class="form-label" for="limit-<?= (int) $b['id'] ?>">Limite mensal (R$)</label><input id="limit-<?= (int) $b['id'] ?>" name="valor" class="form-control" inputmode="decimal" required value="<?= H::escape(number_format($limit / 100, 2, ',', '')) ?>"></div>
    <div class="col-sm-4 d-flex align-items-end"><button class="btn btn-uai-primary w-100">Salvar limite</button></div>
</form></details>
<p class="small text-secondary mt-3 mb-0">Após as pendências: <?= Money::format($limit - $used - (int) $b['pendente']) ?> disponíveis neste limite.</p><form class="mt-3" method="post" action="<?= H::escape($basePath.'/planejamento/'.$b['id'].'/remover') ?>" data-confirm="Remover o limite desta categoria neste mês?"><?= H::fields($csrfToken) ?><input type="hidden" name="mes" value="<?= H::escape($month) ?>"><button class="btn btn-sm btn-outline-secondary">Remover limite</button></form></div></article>
<?php endforeach; ?>
<?php if (!$budgets): ?><div class="empty-state"><h2 class="h4">Qual é seu plano para <?= H::escape($month) ?>?</h2><p>Comece pelas categorias mais importantes. Você pode ajustar os limites depois.</p></div><?php endif; ?>
<p class="small text-secondary">Realizado usa a data de competência. Compras parceladas no cartão entram por parcela; pagamentos de fatura e transferências não contam novamente. Pendências aparecem separadas.</p>
</div><div class="col-xl-4"><section class="card"><div class="card-body"><h2 class="h4">Definir limite</h2><form method="post" action="<?= H::escape($basePath.'/planejamento') ?>" class="vstack gap-3"><?= H::fields($csrfToken) ?><input type="hidden" name="mes" value="<?= H::escape($month) ?>"><div><label class="form-label" for="budget-group">Categoria</label><select id="budget-group" class="form-select" name="grupo_id" required><option value="">Selecione</option><?php foreach ($groups as $id=>$name): ?><option value="<?= (int)$id ?>" <?= (int)($old['grupo_id'] ?? 0)===(int)$id ? 'selected' : '' ?>><?= H::escape($name) ?></option><?php endforeach; ?></select></div><div><label for="budget-value" class="form-label">Limite mensal (R$)</label><input id="budget-value" name="valor" class="form-control" inputmode="decimal" required value="<?= H::escape($old['valor'] ?? '') ?>"></div><button class="btn btn-uai-primary">Salvar limite</button><p class="small text-secondary mb-0">Se a categoria já tem um limite neste mês, ele será atualizado.</p></form></div></section>
<form method="post" class="mt-3" action="<?= H::escape($basePath.'/planejamento/copiar') ?>"><?= H::fields($csrfToken) ?><input type="hidden" name="mes" value="<?= H::escape($month) ?>"><button class="btn btn-outline-secondary w-100">Copiar limites do mês anterior</button></form></div></div>
