<?php use App\Core\Html as H; ?>
<div class="page-heading"><div><p class="eyebrow">MÉTODOS PARA TOMAR DECISÕES</p><h1>Estratégias financeiras</h1><p class="text-secondary">Escolha um método simples, teste por alguns meses e adapte-o à sua realidade.</p></div><a class="btn btn-outline-secondary" href="<?= H::escape($basePath . '/planejamento') ?>">Definir limites</a></div>
<div class="strategy-note mb-4"><strong>Antes de escolher:</strong> estratégias são guias de organização, não regras rígidas nem recomendação de investimento. Priorize despesas essenciais, dívidas caras e uma reserva adequada ao seu contexto.</div>
<div class="row g-4">
<?php foreach ([
    ['50 · 30 · 20', '50% para necessidades, 30% para desejos e 20% para objetivos financeiros.', 'É uma porta de entrada fácil: mostra rapidamente se o custo de vida está ocupando espaço demais.', 'Quem quer uma referência simples para equilibrar gastos, reserva e investimentos.', 'Compare suas categorias no relatório de Análises; use Planejamento para dar limites às despesas variáveis.'],
    ['Orçamento base zero', 'Cada real da receita recebe uma função: contas, metas, investimentos ou lazer; ao final, a sobra planejada é zero.', 'Evita que dinheiro sem destino desapareça em pequenos gastos e dá prioridade ao que importa.', 'Quem recebe valor previsível e quer controle detalhado do mês.', 'Planeje primeiro os gastos fixos, depois as metas e deixe uma categoria para imprevistos.'],
    ['Pague-se primeiro', 'Transfira um valor definido para reserva ou investimento logo após receber, antes dos gastos discricionários.', 'Transforma objetivos futuros em uma conta prioritária, em vez de depender do que sobrar.', 'Quem consegue guardar algum valor, mas costuma gastar a sobra.', 'Registre o investimento e crie uma recorrência ou lembrete para o aporte mensal.'],
    ['Sistema de envelopes', 'Defina um teto para categorias variáveis, como mercado, lazer e transporte; quando acabar, pare ou realoque conscientemente.', 'Torna o limite visível no dia a dia e reduz decisões por impulso.', 'Quem percebe que pequenas compras são o principal vazamento.', 'Crie limites mensais nas categorias e acompanhe o percentual usado em Planejamento.'],
    ['60 · 20 · 20', '60% para necessidades, 20% para objetivos financeiros e 20% para estilo de vida.', 'Reserva uma parcela maior para futuro; pode ser útil quando a renda permite acelerar metas.', 'Quem já cobre o essencial e quer aumentar aportes sem eliminar lazer.', 'Use como meta gradual: aumente a fatia de objetivos aos poucos, sem comprometer contas essenciais.'],
] as [$name, $rule, $why, $bestFor, $how]): ?>
<div class="col-md-6 col-xl-4"><article class="card strategy-card h-100"><div class="card-body"><p class="eyebrow">ESTRATÉGIA</p><h2 class="h4"><?= H::escape($name) ?></h2><p class="strategy-rule"><?= H::escape($rule) ?></p><dl><dt>Por que usar</dt><dd><?= H::escape($why) ?></dd><dt>Faz sentido para</dt><dd><?= H::escape($bestFor) ?></dd><dt>Como aplicar no UaiMoney</dt><dd><?= H::escape($how) ?></dd></dl></div></article></div>
<?php endforeach; ?>
</div>
