<?php

declare(strict_types=1);
require __DIR__ . '/run.php';
$repo = new App\Repositories\MovementRepository($db);
$service = new App\Services\MovementService($repo, $categories, $accounts, $tx, $cardService, $installment, $recurrence);
$initial = $count;
$balance = (int) $accounts->findById($a, 1)['saldo_atual_centavos'];
$input = ['tipo'=>'despesa','subgrupo_id'=>$expense['id'],'conta_id'=>$a,'descricao'=>'CRUD isolado','valor'=>'20','data'=>'2025-04-10','status'=>'efetivada','meio_pagamento'=>'pix','_operation'=>bin2hex(random_bytes(16))];
$service->create(1, $input);
$id = (int) $db->query('SELECT MAX(id) FROM transacoes')->fetchColumn();
$service->create(1, $input);
check((int)$db->query('SELECT MAX(id) FROM transacoes')->fetchColumn()===$id, 'Create replay');
check((int)$accounts->findById($a,1)['saldo_atual_centavos']===$balance-2000, 'Create balance');
$edit = array_replace($input,['valor'=>'30','data_competencia'=>'2025-04-10','data_vencimento'=>'2025-04-10','data_efetivacao'=>'2025-04-10','versao'=>1,'_operation'=>bin2hex(random_bytes(16))]);
$service->update(1,$id,$edit);
check((int)$accounts->findById($a,1)['saldo_atual_centavos']===$balance-3000, 'Edit realized balance');
rejects(fn()=>$service->update(1,$id,array_replace($edit,['_operation'=>bin2hex(random_bytes(16))])), 'Stale edit');
rejects(fn()=>$service->delete(2,$id,['versao'=>2]), 'Foreign delete');
$wallet->refund(1,$id,['valor'=>'5','data'=>'2025-04-11','motivo'=>'Estorno CRUD']);
$before=$reports->totals(1,'2025-04-01','2025-04-30');
$version=(int)$repo->find(1,$id)['versao'];
$service->delete(1,$id,['versao'=>$version]);
check((int)$accounts->findById($a,1)['saldo_atual_centavos']===$balance, 'Delete removes original and refund');
check($ledger->transaction(1,$id)===null, 'Hidden detail');
check((new App\Repositories\ActivityRepository($db))->count(1,['q'=>'CRUD isolado','lixeira'=>'1'])===1, 'Trash visibility');
$after=$reports->totals(1,'2025-04-01','2025-04-30');
check((int)$before['despesas']-(int)$after['despesas']===2500, 'Net spending removed');
$service->restore(1,$id,['versao'=>$version+1]);
check((int)$accounts->findById($a,1)['saldo_atual_centavos']===$balance-2500, 'Restore balance');
check(count($ledger->history(1,$id))===3, 'Audit history');
rejects(fn()=>$service->update(1,$id,array_replace($edit,['versao'=>$version+2,'valor'=>'1','_operation'=>bin2hex(random_bytes(16))])), 'Below refund rejected');
$service->create(1,array_replace($input,['descricao'=>'Parcelas CRUD','modo'=>'parcelado','parcelas'=>3,'_operation'=>bin2hex(random_bytes(16))]));
$items=$db->query("SELECT * FROM transacoes WHERE descricao='Parcelas CRUD' ORDER BY id")->fetchAll();
check(count($items)===3 && array_sum(array_column($items,'valor_centavos'))===2000, 'Cash installments exact cents');
$service->delete(1,(int)$items[0]['id'],['versao'=>1]);
check((new App\Repositories\ActivityRepository($db))->count(1,['q'=>'Parcelas CRUD'])===2, 'Other installments preserved');
$newCard=$cardService->save(1,null,['nome'=>'CRUD cartão','limite'=>'1000','dia_fechamento'=>20,'dia_vencimento'=>5]);
$service->create(1,array_replace($input,['cartao_id'=>$newCard,'meio_pagamento'=>'credito','observacao'=>'Nota preservada','_operation'=>bin2hex(random_bytes(16))]));
$cardId=(int)$db->query('SELECT MAX(id) FROM transacoes')->fetchColumn();
$purchase=$repo->find(1,$cardId);
check($purchase['observacao']==='Nota preservada','Card notes');
$invoiceId=(int)$purchase['fatura_id'];
$cardService->pay(1,$invoiceId,['conta_id'=>$a,'valor'=>'10','data'=>'2025-04-12']);
$service->delete(1,$cardId,['versao'=>1]);
check((int)$cards->invoice(1,$invoiceId)['total']===0 && (int)$cards->invoice(1,$invoiceId)['pago']===1000,'Payment survives deletion');
$service->restore(1,$cardId,['versao'=>2]);
check((int)$cards->invoice(1,$invoiceId)['total']===2000,'Invoice restored');
check($db->query('PRAGMA foreign_key_check')->fetchAll()===[],'Relationships preserved');
echo 'OK: '.($count-$initial)." verificações do CRUD.\n";

