<?php
declare(strict_types=1);
require dirname(__DIR__).'/vendor/autoload.php';
date_default_timezone_set('America/Sao_Paulo');
use App\Core\Money;
use App\Core\FinancialDate;
use App\Repositories\{AccountRepository,AccountShareRepository,ActivityRepository,CardRepository,CategoryRepository,InstallmentRepository,LedgerRepository,RecurrenceRepository,ReportRepository,TransactionRepository};
use App\Services\{CardService,InstallmentService,LedgerService,PlanningService,RecurrenceService,TransactionService};
use App\Services\PublicAccountExportService;

$count=0;
function check(bool $condition,string $message): void { global $count; if(!$condition) throw new RuntimeException($message); $count++; }
function rejects(callable $work,string $message): void { try { $work(); } catch(DomainException) { check(true,$message); return; } throw new RuntimeException('Expected rejection: '.$message); }
$db=new PDO('sqlite::memory:',null,null,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);
$db->exec('PRAGMA foreign_keys=ON');
foreach(glob(dirname(__DIR__).'/database/migrations/*.php') as $file) {
    $db->beginTransaction(); (require $file)($db); $db->commit();
}
$db->exec("INSERT INTO usuarios(nome,login,email,senha_hash) VALUES('Ana','ana','ana@example.test','hash'),('Bia','bia','bia@example.test','hash')");
$accounts=new AccountRepository($db); $categories=new CategoryRepository($db); $ledger=new LedgerRepository($db); $cards=new CardRepository($db); $reports=new ReportRepository($db); $transactions=new TransactionRepository($db);
$cardService=new CardService($cards,$accounts,$categories); $wallet=new LedgerService($ledger,$accounts,$cards,$cardService); $planning=new PlanningService($reports); $tx=new TransactionService($transactions,$categories,$accounts);
$ledger->startCategories(1); $ledger->startCategories(2); $ledger->startCategories(1);
$a=$accounts->create(1,'Principal','corrente',null,100000,'2020-01-01'); $b=$accounts->create(1,'Carteira','dinheiro',null,0,'2020-01-01'); $foreign=$accounts->create(2,'Outra','corrente',null,30000,'2020-01-01');
$expense=array_values(array_filter($reports->categories(1),fn($c)=>$c['tipo']==='despesa'))[0];
$foreignCategory=$reports->categories(2)[0];
check(Money::toCents('1.234,56')===123456,'BR money'); check(Money::toCents('10.01')===1001,'Decimal money'); check(Money::format(-101)==='- R$ 1,01','Negative format');
rejects(fn()=>Money::toCents('1e10'),'Scientific notation'); rejects(fn()=>Money::toCents('99999999999999999999999'),'Overflow'); rejects(fn()=>Money::toCents('1,234'),'Fractions of a cent');
check(FinancialDate::day('2024-02',31)==='2024-02-29','Leap year'); check(FinancialDate::day('2025-02',31)==='2025-02-28','February clamp');
$wallet->transfer(1,['origem_id'=>$a,'destino_id'=>$b,'valor'=>'100','data'=>'2025-01-10']);
check((int)$accounts->findById($a,1)['saldo_atual_centavos']===90000,'Transfer source'); check((int)$accounts->findById($b,1)['saldo_atual_centavos']===10000,'Transfer destination');
check((int)$reports->totals(1,'2025-01-01','2025-12-31')['despesas']===0,'Transfer not spending');
rejects(fn()=> $wallet->transfer(1,['origem_id'=>$a,'destino_id'=>$foreign,'valor'=>'100','data'=>'2025-01-10']),'Foreign destination');
rejects(fn()=> $wallet->transfer(1,['origem_id'=>$a,'destino_id'=>$a,'valor'=>'100','data'=>'2025-01-10']),'Same account');
$card=$cardService->save(1,null,['nome'=>'Meu cartão','limite'=>'2000','dia_fechamento'=>20,'dia_vencimento'=>5,'conta_pagamento_id'=>$a]);
$cardData=$cardService->get(1,$card);
check($cardService->cycle($cardData,'2025-01-19')==='2025-01','Before close'); check($cardService->cycle($cardData,'2025-01-20')==='2025-02','On close'); check($cardService->cycle($cardData,'2025-12-31')==='2026-01','Year rollover');
$purchase=['cartao_id'=>$card,'subgrupo_id'=>$expense['id'],'data'=>'2025-01-10','descricao'=>'Compra parcelada','valor'=>'100.01','parcelas'=>3];
$cardService->purchase(1,$purchase);
$inv=array_reverse($cards->invoices(1,$card));
check(count($inv)===3,'Three invoices'); check(array_column($inv,'total')===[3334,3334,3333],'Exact cents'); check($inv[0]['data_vencimento']==='2025-02-05','Due next month');
check((int)$cards->list(1)[0]['utilizado']===10001,'Full installment commitment'); check((int)$accounts->findById($a,1)['saldo_atual_centavos']===90000,'No bank debit on purchase');
$cardService->pay(1,(int)$inv[0]['id'],['conta_id'=>$a,'data'=>'2025-02-01','valor'=>'10']);
check((int)$accounts->findById($a,1)['saldo_atual_centavos']===89000,'Payment debits account');
check((int)$reports->totals(1,'2025-01-01','2025-12-31')['despesas']===10001,'No double spending');
check((int)$cards->list(1)[0]['utilizado']===9001,'Limit released');
rejects(fn()=> $cardService->pay(1,(int)$inv[0]['id'],['conta_id'=>$a,'data'=>'2025-02-01','valor'=>'100']),'Overpayment');
rejects(fn()=> $cardService->pay(2,(int)$inv[0]['id'],['conta_id'=>$foreign,'data'=>'2025-02-01','valor'=>'1']),'Foreign invoice');
rejects(fn()=> $cardService->purchase(1,array_replace($purchase,['subgrupo_id'=>$foreignCategory['id']])),'Foreign category');
$before=(int)$db->query('SELECT COUNT(*) FROM transacoes')->fetchColumn();
rejects(fn()=> $cardService->purchase(1,$purchase),'Closed invoice rejects new purchases');
check((int)$db->query('SELECT COUNT(*) FROM transacoes')->fetchColumn()===$before,'Failed purchase is atomic');
$t=$cards->items(1,(int)$inv[0]['id'])[0];
$wallet->refund(1,(int)$t['id'],['valor'=>'3.34','data'=>'2025-02-10','motivo'=>'Devolução','fatura_mes'=>'2025-02']);
check((int)$cards->invoice(1,(int)$inv[1]['id'])['total']===3000,'Refund credited to selected invoice'); check((int)$reports->totals(1,'2025-01-01','2025-12-31')['despesas']===9667,'Refund reduces spending');
rejects(fn()=> $tx->cancel(1,(int)$t['id']),'Realized card cannot be cancelled');
$cash=$tx->create(1,(int)$expense['id'],$a,'Mercado','20','2025-03-01','2025-03-01','2025-03-01','efetivada','pix',null);
$wallet->refund(1,$cash,['valor'=>'5','data'=>'2025-03-02','motivo'=>'Devolução parcial']);
check((int)$accounts->findById($a,1)['saldo_atual_centavos']===87500,'Cash refund returns to source account');
rejects(fn()=> $wallet->refund(1,$cash,['valor'=>'16','data'=>'2025-03-02','motivo'=>'Excedente']),'Refund cannot exceed remainder');
rejects(fn()=> $wallet->refund(2,$cash,['valor'=>'1','data'=>'2025-03-02','motivo'=>'Outro usuário']),'Foreign refund');
$wallet->reconcile(1,['conta_id'=>$a,'saldo'=>'900','motivo'=>'Conferência do extrato']); check((int)$accounts->findById($a,1)['saldo_atual_centavos']===90000,'Reconciliation');
$wallet->reconcile(1,['conta_id'=>$a,'saldo'=>'900','motivo'=>'Conferência repetida']); check((int)$accounts->findById($a,1)['saldo_atual_centavos']===90000,'Zero adjustment');
check((int)$reports->totals(1,'2025-01-01',date('Y-m-d'))['despesas']===11167,'Adjustments excluded from consumption');
$planning->save(1,['mes'=>'2025-01','grupo_id'=>$expense['grupo_id'],'valor'=>'500']);
$planning->save(1,['mes'=>'2025-01','grupo_id'=>$expense['grupo_id'],'valor'=>'600']); check(count($reports->budgets(1,'2025-01'))===1,'Budget upsert');
$planning->copy(1,'2025-02'); $planning->copy(1,'2025-02'); check(count($reports->budgets(1,'2025-02'))===1,'Budget copy idempotent'); check($reports->budgets(2,'2025-02')===[],'Budget isolation');
$installment=new InstallmentService($db,new InstallmentRepository($db),$transactions,$categories,$accounts);
$pid=$installment->create(1,(int)$expense['id'],$a,'Carnê','10.01',3,'2025-01-31','boleto',null);
$dates=$db->query('SELECT data_vencimento FROM transacoes WHERE parcelamento_id='.(int)$pid.' ORDER BY numero_parcela')->fetchAll(PDO::FETCH_COLUMN);
check($dates===['2025-01-31','2025-02-28','2025-03-31'],'Installment anchor day');
$recurrence=new RecurrenceService($db,new RecurrenceRepository($db),$transactions,$categories,$accounts);
$rid=$recurrence->create(1,(int)$expense['id'],$a,'Assinatura','10','mensal',1,'2025-01-31',3,'pix',null);
$recurrence->processDue(1); $recurrence->processDue(1);
check((int)$db->query('SELECT COUNT(*) FROM transacoes WHERE recorrencia_id='.(int)$rid)->fetchColumn()===3,'Recurring idempotency');
check($accounts->findById($a,2)===null && $ledger->transaction(2,$cash)===null && $cards->find(2,$card)===null,'Read isolation');
check($db->query('PRAGMA foreign_key_check')->fetchAll()===[],'Foreign key integrity');
$activity=new ActivityRepository($db); check($activity->count(2,[])===0,'Activity isolation');
check($activity->count(1,['q'=>"' OR 1=1 --"])===0,'Search parameter binding');
$key=bin2hex(random_bytes(16));
$payment=['conta_id'=>$a,'data'=>'2025-02-02','valor'=>'1','_operation'=>$key];
$before=(int)$accounts->findById($a,1)['saldo_atual_centavos'];
$cardService->pay(1,(int)$inv[0]['id'],$payment); $cardService->pay(1,(int)$inv[0]['id'],$payment);
check((int)$accounts->findById($a,1)['saldo_atual_centavos']===$before-100,'Durable payment idempotency');
$before=(int)$accounts->findById($a,1)['saldo_atual_centavos'];
$transfer=['origem_id'=>$a,'destino_id'=>$b,'valor'=>'1','data'=>'2025-04-01','_operation'=>bin2hex(random_bytes(16))];
$wallet->transfer(1,$transfer); $wallet->transfer(1,$transfer);
check((int)$accounts->findById($a,1)['saldo_atual_centavos']===$before-100,'Durable transfer idempotency');
$wallet->refund(1,(int)$t['id'],['valor'=>'30','data'=>'2025-04-10','motivo'=>'Devolução restante','fatura_mes'=>'2025-04']);
$creditInvoice=$cards->invoices(1,$card)[0];
$cardService->carryCredit(1,(int)$creditInvoice['id'],'2025-05');
check((int)$cards->invoice(1,(int)$creditInvoice['id'])['total']===0,'Credit source settled');
check((int)$cards->invoices(1,$card)[0]['total']===-3000,'Credit carried forward');
rejects(fn()=> $cardService->carryCredit(1,(int)$creditInvoice['id'],'2025-05'),'Credit cannot move twice');
rejects(fn()=> $tx->create(1,(int)$expense['id'],$a,'Futuro','10',date('Y-m-d'),date('Y-m-d'),'2099-01-01','efetivada','pix',null),'Realized future cash rejected');
rejects(fn()=> $tx->create(1,(int)$expense['id'],$a,'Crédito incorreto','10',date('Y-m-d'),date('Y-m-d'),date('Y-m-d'),'efetivada','credito',null),'Credit requires card flow');
$newRec=$recurrence->create(1,(int)$expense['id'],$a,'Editar futuro','11','mensal',1,date('Y-m-d'),null,'pix',null);
$recurrence->processDue(1);
$generated=$db->query('SELECT * FROM transacoes WHERE recorrencia_id='.(int)$newRec)->fetchAll();
$next=date('Y-m-d',strtotime('+1 month'));
$recurrence->update(1,$newRec,(int)$expense['id'],$a,'Editar futuro','22','semanal',1,$next,null,'pix',null);
check($db->query('SELECT * FROM transacoes WHERE recorrencia_id='.(int)$newRec)->fetchAll()===$generated,'Recurrence edits preserve historical transactions');
$limiter=new \App\Core\RateLimiter($db);
$limiter->hit('test','key',2); $limiter->hit('test','key',2);
rejects(fn()=> $limiter->hit('test','key',2),'Access rate limiting');
$limiter->clear('test','key'); $limiter->hit('test','key',2); check(true,'Access limit reset');
$pageItems=$activity->list(1,[]); check(count($pageItems)<=51,'Pagination bounded');
$shares=new AccountShareRepository($db);
$rawToken=rtrim(strtr(base64_encode(random_bytes(32)),'+/','-_'),'=');
$shares->save(1,$a,hash('sha256',$rawToken),substr($rawToken,-8),password_hash('segredo',PASSWORD_DEFAULT));
$publicShare=$shares->findByToken($rawToken);
check($publicShare!==null && (int)$publicShare['conta_id']===$a,'Public share resolves secure token');
check($shares->findByToken($rawToken.'x')===null,'Invalid public share token rejected');
$publicTotals=$shares->totals($publicShare,['inicio'=>'2025-03-01','fim'=>'2025-03-31','tipo'=>'','q'=>'']);
check((int)$publicTotals['saidas']===2000 && (int)$publicTotals['entradas']===500,'Shared statement totals respect period and refund');
check($shares->entries($publicShare,['inicio'=>'','fim'=>'','tipo'=>'entrada','q'=>''],1)!==[],'Shared statement filters entries');
$publicExportEntries=$shares->exportEntries($publicShare,['inicio'=>'2025-03-01','fim'=>'2025-03-31','tipo'=>'','q'=>'']);
$publicExporter=new PublicAccountExportService();
check(str_starts_with($publicExporter->csv($publicExportEntries),"\xEF\xBB\xBFData"),'Public CSV export includes UTF-8 header');
check(str_starts_with($publicExporter->pdf('Principal',$publicExportEntries,$publicTotals,'março de 2025'),'%PDF-'),'Public PDF export is valid');
check(str_starts_with($publicExporter->excel('Principal',$publicExportEntries,$publicTotals,'março de 2025'),'PK'),'Public Excel export is valid');
$shares->disable(1,$a);
check($shares->findByToken($rawToken)===null,'Disabled public share rejected');
check(Money::toSignedCents('-1.234,56')===-123456,'Negative account balances');
rejects(fn()=> Money::toSignedCents('--10'),'Invalid signed amount');
rejects(fn()=> $planning->save(2,['mes'=>'2025-01','grupo_id'=>$expense['grupo_id'],'valor'=>'100']),'Foreign budget category');
$monthly=$reports->monthly(1,'2025-01-01','2025-06-30');
check(count($monthly)===6 && $monthly[5]['nome']==='2025-06' && (int)$monthly[5]['despesas']===0,'Analytics fills months without activity');
$total=$reports->totals(1,'2025-01-01','2025-06-30');
check(array_sum(array_column($monthly,'despesas'))===(int)$total['despesas'],'Monthly chart reconciles net refunds');
foreach(['categoria','subcategoria'] as $dimension) {
    $breakdown=$reports->breakdown(1,'2025-01-01','2025-06-30',$dimension);
    check(array_sum(array_column($breakdown,'despesas'))===(int)$total['despesas'],'Category charts reconcile totals');
}
$filtered=$reports->monthly(1,'2025-01-01','2025-06-30',['conta_id'=>$foreign]);
check(array_sum(array_column($filtered,'despesas'))===0,'Analytics cannot expose foreign account activity');
$partial=$reports->monthly(1,'2025-03-02','2025-03-02',['subgrupo_id'=>$expense['id']]);
check((int)$partial[0]['despesas']===-500,'Partial month chart preserves negative net refunds and filters');
$period=\App\Services\AnalyticsService::period([], '2026-09-23');
check($period['start']==='2026-09-01' && $period['end']==='2026-09-23' && $period['partial'],'Current month stops today');
check($period['previousStart']==='2026-08-01' && $period['previousEnd']==='2026-08-23','Partial month compares matching days');
$period=\App\Services\AnalyticsService::period(['periodo'=>'anterior'], '2024-03-15');
check($period['start']==='2024-02-01' && $period['end']==='2024-02-29' && $period['previousEnd']==='2024-01-31','Full calendar month comparison and leap year');
$period=\App\Services\AnalyticsService::period(['periodo'=>'semestre'], '2026-02-10');
check($period['start']==='2025-09-01' && $period['end']==='2026-02-10','Six month preset crosses year');
$period=\App\Services\AnalyticsService::period(['inicio'=>'2025-03-20','fim'=>'2025-03-10'], '2026-09-23');
check($period['start']==='2025-03-10' && $period['previousStart']==='2025-02-27' && $period['previousEnd']==='2025-03-09','Custom comparison uses preceding equal duration');
$entries=$reports->entries(1,'2025-03-02','2025-03-02',['subgrupo_id'=>$expense['id']]);
check(count($entries)===1 && (int)$entries[0]['valor_centavos']===-500 && (int)$entries[0]['transacao_id']===$cash,'Audit includes refund on its own date and links original transaction');
check($reports->entries(2,'2025-03-01','2025-03-31',['conta_id'=>$a])===[],'Audit user isolation');
check($reports->entries(1,'2025-03-01','2025-03-31',[],2)===[],'Audit respects page offset');
foreach($reports->breakdown(1,'2025-03-01','2025-03-31','subcategoria') as $row) {
    check((int)$row['grupo_id']===(int)$expense['grupo_id'],'Subcategory drilldown preserves parent category');
}
echo "OK: $count verificações financeiras e de isolamento.\n";
