<?php use App\Core\Html as H; use App\Core\Money; $remaining=(int)$invoice['total']-(int)$invoice['pago']; ?>
<a class="back-link" href="<?= H::escape($basePath.'/cartoes/'.$invoice['cartao_id']) ?>">← <?= H::escape($invoice['cartao_nome']) ?></a>
<div class="page-heading"><div><p class="eyebrow">FATURA · <?= H::escape($invoice['competencia']) ?></p><h1><?= Money::format($remaining) ?></h1><p class="text-secondary"><?= $remaining<0 ? 'Crédito nesta fatura' : 'Saldo a pagar' ?> · Vence em <?= H::date($invoice['data_vencimento']) ?></p></div><span class="badge text-bg-secondary"><?= H::escape($invoice['status']) ?></span></div>
<div class="row g-4"><div class="col-xl-8"><section class="card"><div class="card-body"><h2 class="h4">Compras desta fatura</h2><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Compra</th><th>Competência</th><th class="text-end">Valor</th></tr></thead><tbody>
<?php foreach ($items as $t): ?><tr><td><a href="<?= H::escape($basePath.'/movimentacoes/'.$t['id']) ?>"><?= H::escape($t['descricao']) ?></a><div class="small text-secondary"><?= H::escape($t['categoria']) ?><?= $t['numero_parcela'] ? ' · Parcela '.(int)$t['numero_parcela'] : '' ?><?= $t['status']==='cancelada' ? ' · Cancelada' : '' ?></div></td><td><?= H::date($t['data_competencia']) ?></td><td class="text-end"><?= Money::format((int)$t['valor_centavos']) ?><?php if ($t['estornado']): ?><div class="small text-secondary">Estornado: <?= Money::format((int)$t['estornado']) ?></div><?php endif; ?></td></tr><?php endforeach; ?>
<?php if (!$items): ?><tr><td colspan="3">Nenhuma compra nesta fatura.</td></tr><?php endif; ?></tbody></table></div><p class="small text-secondary mb-0">Total líquido: <?= Money::format((int)$invoice['total']) ?> · Pagamentos: <?= Money::format((int)$invoice['pago']) ?>. Créditos de estorno podem se referir a compras de outras faturas.</p></div></section>
<section class="card mt-4"><div class="card-body"><h2 class="h4">Pagamentos registrados</h2><?php if (!$payments): ?><p class="text-secondary">Nenhum pagamento até agora.</p><?php endif; ?><?php foreach ($payments as $p): ?><div class="list-row"><div><?= H::escape($p['conta_nome']) ?><small class="d-block text-secondary"><?= H::date($p['data_pagamento']) ?></small></div><strong><?= Money::format((int)$p['valor_centavos']) ?></strong></div><?php endforeach; ?></div></section></div>
<div class="col-xl-4"><section class="card"><div class="card-body"><h2 class="h4"><?= $remaining>0 ? 'Pagar fatura' : 'Fatura sem saldo devedor' ?></h2>
<?php if ($remaining>0): ?><p class="text-secondary">Você pode pagar o total ou uma parte. O primeiro pagamento fecha a fatura.</p><form method="post" action="<?= H::escape($basePath.'/faturas/'.$invoice['id'].'/pagar') ?>" class="vstack gap-3"><?= H::fields($csrfToken) ?>
<div><label for="pay-account" class="form-label">Conta de pagamento</label><select id="pay-account" name="conta_id" class="form-select" required><option value="">Selecione</option><?php foreach ($accounts as $a): ?><option value="<?= (int)$a['id'] ?>" <?= (int)($old['conta_id'] ?? $invoice['conta_pagamento_id'])===(int)$a['id'] ? 'selected' : '' ?>><?= H::escape($a['nome']) ?></option><?php endforeach; ?></select></div>
<div><label for="pay-amount" class="form-label">Valor (R$)</label><input id="pay-amount" name="valor" class="form-control" inputmode="decimal" required value="<?= H::escape($old['valor'] ?? number_format($remaining/100,2,'.','')) ?>"></div>
<div><label for="pay-date" class="form-label">Data do pagamento</label><input id="pay-date" name="data" class="form-control" type="date" required max="<?= date('Y-m-d') ?>" value="<?= H::escape($old['data'] ?? date('Y-m-d')) ?>"></div><button class="btn btn-uai-primary">Registrar pagamento</button></form><?php else: ?><p class="text-secondary">Os pagamentos e as compras permanecem disponíveis para consulta.</p><?php endif; ?>
<?php if ($invoice['status']==='aberta'): ?><form class="mt-3" method="post" action="<?= H::escape($basePath.'/faturas/'.$invoice['id'].'/fechar') ?>" data-confirm="Fechar a fatura? Novas compras não poderão ser adicionadas a ela."><?= H::fields($csrfToken) ?><button class="btn btn-outline-secondary w-100">Fechar fatura</button></form><?php endif; ?></div></section></div></div>

<?php if($remaining<0): ?><section class="card mt-4"><div class="card-body"><h2 class="h4">Usar crédito em outra fatura</h2><p class="text-secondary">Transporte <?= Money::format(-$remaining) ?> para uma fatura posterior do mesmo cartão.</p><form method="post" action="<?= H::escape($basePath.'/faturas/'.$invoice['id'].'/credito') ?>" class="d-flex gap-3 align-items-end flex-wrap"><?= H::fields($csrfToken) ?><div><label class="form-label" for="credit-month">Mês de fechamento de destino</label><input id="credit-month" type="month" name="mes" class="form-control" required value="<?= H::escape(\App\Core\FinancialDate::shift($invoice['competencia'],1)) ?>"></div><button class="btn btn-uai-primary">Transportar crédito</button></form></div></section><?php endif; ?>
<?php if($credits): ?><section class="card mt-4"><div class="card-body"><h2 class="h4">Créditos entre faturas</h2><?php foreach($credits as $credit): ?><p><?= (int)$credit['origem_id']===(int)$invoice['id'] ? 'Enviado para' : 'Recebido de' ?> <a href="<?= H::escape($basePath.'/faturas/'.((int)$credit['origem_id']===(int)$invoice['id'] ? $credit['destino_id'] : $credit['origem_id'])) ?>">outra fatura</a>: <?= Money::format((int)$credit['valor_centavos']) ?></p><?php endforeach; ?></div></section><?php endif; ?>
