<?php use App\Core\Html as H; use App\Core\Money; ?>
<a class="back-link" href="<?= H::escape($basePath.'/cartoes') ?>">← Todos os cartões</a>
<div class="page-heading"><div><p class="eyebrow">CARTÃO DE CRÉDITO</p><h1><?= H::escape($card['nome']) ?></h1><p class="text-secondary">Fecha dia <?= (int)$card['dia_fechamento'] ?> · Vence dia <?= (int)$card['dia_vencimento'] ?></p></div><a class="btn btn-uai-primary" href="#purchase">+ Nova compra</a></div>
<section class="card mb-4"><div class="card-body"><h2 class="h4">Faturas</h2>
<?php if (!$invoices): ?><p class="empty-state">As faturas aparecem após a primeira compra.</p><?php else: ?><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Fechamento</th><th>Vencimento</th><th>Total</th><th>Pago</th><th>Saldo / crédito</th><th>Situação</th></tr></thead><tbody>
<?php foreach ($invoices as $f): $remaining=(int)$f['total']-(int)$f['pago']; ?><tr><td><a href="<?= H::escape($basePath.'/faturas/'.$f['id']) ?>"><?= H::date($f['data_fechamento']) ?></a></td><td><?= H::date($f['data_vencimento']) ?></td><td><?= Money::format((int)$f['total']) ?></td><td><?= Money::format((int)$f['pago']) ?></td><td><?= Money::format($remaining) ?></td><td><span class="badge text-bg-<?= $remaining<=0 ? 'success' : 'secondary' ?>"><?= $remaining<0 ? 'Crédito' : ($remaining===0 ? 'Quitada' : ((int)$f['pago']>0 ? 'Pagamento parcial' : ($f['status']==='aberta' ? 'Aberta' : 'Fechada'))) ?></span></td></tr><?php endforeach; ?>
</tbody></table></div><?php endif; ?></div></section>
<?php if ($card['ativo']): ?>
<section class="card" id="purchase"><div class="card-body"><h2 class="h4">Nova compra</h2><p class="text-secondary">O valor total compromete o limite. O saldo bancário muda apenas ao pagar a fatura.</p>
<form method="post" action="<?= H::escape($basePath.'/cartoes/compras') ?>" class="row g-3"><?= H::fields($csrfToken) ?><input type="hidden" name="cartao_id" value="<?= (int)$card['id'] ?>">
<div class="col-md-8"><label for="purchase-description" class="form-label">Descrição</label><input id="purchase-description" name="descricao" class="form-control" required maxlength="160" value="<?= H::escape($old['descricao'] ?? '') ?>" placeholder="Ex.: Compra no mercado"></div>
<div class="col-md-4"><label for="purchase-amount" class="form-label">Valor total (R$)</label><input id="purchase-amount" name="valor" class="form-control" inputmode="decimal" required value="<?= H::escape($old['valor'] ?? '') ?>"></div>
<div class="col-md-6"><label for="purchase-category" class="form-label">Categoria</label><select id="purchase-category" class="form-select" name="subgrupo_id" required><option value="">Selecione</option><?php foreach ($categories as $c): if ($c['tipo']!=='despesa') continue; ?><option value="<?= (int)$c['id'] ?>" <?= (string)($old['subgrupo_id'] ?? '')===(string)$c['id'] ? 'selected' : '' ?>><?= H::escape($c['grupo_nome'].' · '.$c['nome']) ?></option><?php endforeach; ?></select></div>
<div class="col-md-3"><label for="purchase-date" class="form-label">Data da compra</label><input id="purchase-date" name="data" class="form-control" type="date" required max="<?= date('Y-m-d') ?>" value="<?= H::escape($old['data'] ?? date('Y-m-d')) ?>"></div>
<div class="col-md-3"><label for="purchase-count" class="form-label">Parcelas</label><input id="purchase-count" name="parcelas" class="form-control" type="number" min="1" max="120" required value="<?= H::escape($old['parcelas'] ?? 1) ?>"></div>
<div class="col-12"><details><summary>Ajustar primeira fatura</summary><p class="small text-secondary mt-2">Compras no dia do fechamento entram na próxima fatura. Se o banco usar outra data, escolha o mês de fechamento. Em compras parceladas, o orçamento considera cada parcela no mês de fechamento.</p><label for="purchase-month" class="form-label">Mês de fechamento da primeira fatura (opcional)</label><input id="purchase-month" name="primeira_fatura" class="form-control" type="month" value="<?= H::escape($old['primeira_fatura'] ?? '') ?>"></details></div>
<div class="col-12"><button class="btn btn-uai-primary">Registrar compra</button></div></form></div></section>
<form method="post" action="<?= H::escape($basePath.'/cartoes/'.$card['id'].'/desativar') ?>" class="mt-4" data-confirm="Desativar este cartão? O histórico será preservado."><?= H::fields($csrfToken) ?><button class="btn btn-outline-secondary btn-sm">Desativar cartão</button></form>
<?php endif; ?>
