<?php use App\Core\Html as H; use App\Core\Money; $returnPath = \App\Core\MovementReturn::path($_GET['voltar'] ?? ''); ?>
<a class="back-link" href="<?= H::escape($basePath.$returnPath.'#lista') ?>">← Movimentações</a><div class="page-heading"><div><p class="eyebrow"><?= H::escape($t['tipo']) ?> · <?= H::escape(['efetivada' => 'Realizada', 'pendente' => 'Pendente', 'cancelada' => 'Cancelada'][$t['status']] ?? $t['status']) ?></p><h1><?= H::escape($t['descricao']) ?></h1><p class="text-secondary"><?= H::escape($t['grupo_nome'].' · '.$t['subgrupo_nome']) ?></p></div><strong class="metric-value"><?= Money::format((int)$t['valor_centavos']) ?></strong></div>
<div class="detail-actions mb-4">
    <a class="btn btn-uai-primary" href="<?= H::escape($basePath . '/movimentacoes/' . $t['id'] . '/editar?voltar=' . urlencode($returnPath)) ?>">Editar movimentação</a>
    <form method="post" action="<?= H::escape($basePath . '/movimentacoes/' . $t['id'] . '/excluir') ?>" data-confirm="Enviar este lançamento e seus efeitos nos saldos para a lixeira? As outras parcelas e recorrências serão mantidas.">
        <?= H::fields($csrfToken) ?>
        <input type="hidden" name="versao" value="<?= (int) $t['versao'] ?>">
        <input type="hidden" name="_retorno" value="<?= H::escape($returnPath) ?>">
        <button class="btn btn-outline-danger">Excluir</button>
    </form>
</div><section class="card mb-4"><div class="card-body"><dl class="row mb-0"><dt class="col-md-3">Data usada nas análises</dt><dd class="col-md-9"><?= H::date($t['data_competencia']) ?></dd><dt class="col-md-3">Vencimento</dt><dd class="col-md-9"><?= H::date($t['data_vencimento']) ?></dd><dt class="col-md-3">Conta / cartão</dt><dd class="col-md-9"><?= H::escape($t['cartao_nome'] ?? $t['conta_nome'] ?? 'Não definido') ?><?php if($t['fatura_id']): ?> · <a href="<?= H::escape($basePath.'/faturas/'.$t['fatura_id']) ?>">Ver fatura</a><?php endif; ?></dd><dt class="col-md-3">Origem</dt><dd class="col-md-9"><?= $t['recorrencia_id'] ? 'Recorrência #'.(int)$t['recorrencia_id'] : ($t['parcelamento_id'] ? 'Parcelamento #'.(int)$t['parcelamento_id'].' · Parcela '.(int)$t['numero_parcela'] : 'Avulsa') ?></dd><dt class="col-md-3">Observações</dt><dd class="col-md-9"><?= H::escape($t['observacao'] ?: '—') ?></dd><dt class="col-md-3">Estornado</dt><dd class="col-md-9"><?= Money::format((int)$t['estornado']) ?></dd></dl>
<?php if(!$t['cartao_id']): ?><form class="mt-3" method="post" action="<?= H::escape($basePath.'/movimentacoes/'.$t['id'].'/duplicar') ?>"><?= H::fields($csrfToken) ?><button class="btn btn-outline-secondary">Duplicar como pendente</button></form><?php endif; ?></div></section>
<div class="row g-4"><?php if($t['status']==='efetivada' && (int)$t['estornado']<(int)$t['valor_centavos']): ?><div class="col-lg-6"><section class="card"><div class="card-body"><h2 class="h4">Registrar estorno</h2><p class="small text-secondary">O original será preservado. O estorno reduz o consumo na data informada.</p><form method="post" action="<?= H::escape($basePath.'/movimentacoes/'.$t['id'].'/estornar') ?>" class="vstack gap-3" data-confirm="Registrar este estorno e preservar o lançamento original?"><?= H::fields($csrfToken) ?><div><label for="refund-amount" class="form-label">Valor (R$)</label><input id="refund-amount" name="valor" class="form-control" inputmode="decimal" required value="<?= H::escape($old['valor'] ?? number_format(((int)$t['valor_centavos']-(int)$t['estornado'])/100,2,'.','')) ?>"></div><div><label for="refund-date" class="form-label">Data do estorno</label><input id="refund-date" name="data" class="form-control" type="date" max="<?= date('Y-m-d') ?>" required value="<?= H::escape($old['data'] ?? date('Y-m-d')) ?>"></div><div><label for="refund-reason" class="form-label">Motivo</label><input id="refund-reason" name="motivo" class="form-control" maxlength="200" required value="<?= H::escape($old['motivo'] ?? '') ?>"></div><?php if($t['cartao_id']): ?><div><label for="refund-month" class="form-label">Mês de fechamento da fatura de crédito (opcional)</label><input id="refund-month" name="fatura_mes" type="month" class="form-control" value="<?= H::escape($old['fatura_mes'] ?? '') ?>"><small class="text-secondary">Deixe vazio para usar o ciclo da data do estorno. Deve ser uma fatura aberta.</small></div><?php endif; ?><button class="btn btn-uai-primary">Registrar estorno</button></form></div></section></div><?php endif; ?>
<?php if($t['cartao_id']): ?><div class="col-lg-6"><section class="card"><div class="card-body"><h2 class="h4">Ajustar fatura</h2><p class="small text-secondary">Para compras sem estorno, entre faturas abertas e sem pagamentos. A competência do gasto será mantida.</p><form class="vstack gap-3" method="post" action="<?= H::escape($basePath.'/movimentacoes/'.$t['id'].'/fatura') ?>"><?= H::fields($csrfToken) ?><div><label for="move-month" class="form-label">Mês de fechamento da fatura correta</label><input id="move-month" name="mes" type="month" class="form-control" required></div><button class="btn btn-outline-secondary">Mover para esta fatura</button></form></div></section></div><?php endif; ?></div>
<section class="card mt-4"><div class="card-body"><h2 class="h4">Histórico de estornos</h2><?php if(!$refunds): ?><p class="text-secondary">Nenhum estorno registrado.</p><?php endif; ?><?php foreach($refunds as $r): ?><div class="list-row"><div><?= H::escape($r['motivo']) ?><small class="d-block text-secondary"><?= H::date($r['data']) ?><?php if($r['fatura_id']): ?> · <a href="<?= H::escape($basePath.'/faturas/'.$r['fatura_id']) ?>">Crédito na fatura</a><?php endif; ?></small></div><strong><?= Money::format((int)$r['valor_centavos']) ?></strong></div><?php endforeach; ?></div></section>

<?php if ($history): ?>
    <section class="card mt-4"><div class="card-body">
        <h2 class="h4">Histórico de alterações</h2>
        <p class="small text-secondary">Últimas 20 alterações deste lançamento. Horários em UTC.</p>
        <?php foreach ($history as $change): ?>
            <div class="list-row"><strong><?= H::escape($change['acao']) ?></strong><time><?= H::date(substr($change['criado_em'], 0, 10)) ?> · <?= H::escape(substr($change['criado_em'], 11, 5)) ?></time></div>
        <?php endforeach; ?>
    </div></section>
<?php endif; ?>
