<?php
use App\Core\Html as H;
use App\Core\Money;

$result=$projection['result']; $series=$result['series']; $complete=$viewMode==='completa';
$duration=static function(int $months):string{if($months===0)return'Meta alcançada';$y=intdiv($months,12);$m=$months%12;$p=[];if($y)$p[]=$y.' '.($y===1?'ano':'anos');if($m)$p[]=$m.' '.($m===1?'mês':'meses');return implode(' e ',$p);};
$month=static fn(string $value):string=>substr($value,5,2).'/'.substr($value,0,4);
$dateLabel=static fn(string $value):string=>implode('/',array_reverse(explode('-',substr($value,0,10))));
$monthsBetween=static function(string $from,string $to):int{$a=new DateTimeImmutable(substr($from,0,7).'-01');$b=new DateTimeImmutable(substr($to,0,7).'-01');return max(0,((int)$b->format('Y')-(int)$a->format('Y'))*12+(int)$b->format('m')-(int)$a->format('m'));};

$history=$projection['history'];
if(!$history)$history=[['valor_centavos'=>(int)$projection['valor_inicial_centavos'],'data_referencia'=>date('Y-m-d')]];
$startDate=(string)$history[0]['data_referencia']; $currentMonth=date('Y-m'); $elapsed=$monthsBetween($startDate,$currentMonth);
$historySeries=[];
foreach($history as $row)$historySeries[]=['months'=>$monthsBetween($startDate,(string)$row['data_referencia']),'month'=>substr((string)$row['data_referencia'],0,7),'balance_cents'=>(int)$row['valor_centavos']];
$lastHistory=end($historySeries);
if(!$lastHistory||$lastHistory['months']!==$elapsed||(int)$lastHistory['balance_cents']!==(int)$projection['valor_inicial_centavos'])$historySeries[]=['months'=>$elapsed,'month'=>$currentMonth,'balance_cents'=>(int)$projection['valor_inicial_centavos']];

$futureSeries=[];
foreach($series as $row){$copy=$row;if($complete)$copy['months']=$elapsed+(int)$row['months'];$futureSeries[]=$copy;}
$chartW=960;$chartH=340;$left=72;$top=24;$plotW=850;$plotH=260;
$maxMonth=max(1,$complete?$elapsed+(int)$result['months']:(int)$result['months']);
$historyMax=max(array_column($historySeries,'balance_cents'));$maxValue=max(1,(int)$result['final_balance_cents'],(int)$result['target_cents'],$historyMax);
$point=static function(array $row,string $key)use($left,$top,$plotW,$plotH,$maxMonth,$maxValue):string{$x=$left+((int)$row['months']/$maxMonth)*$plotW;$y=$top+(1-((int)$row[$key]/$maxValue))*$plotH;return number_format($x,1,'.','').','.number_format($y,1,'.','');};
$balancePoints=implode(' ',array_map(fn($row)=>$point($row,'balance_cents'),$futureSeries));
$contributionPoints=implode(' ',array_map(fn($row)=>$point($row,'contributed_cents'),$futureSeries));
$historyPoints=implode(' ',array_map(fn($row)=>$point($row,'balance_cents'),$historySeries));
$firstFuture=explode(',',$point($futureSeries[0],'balance_cents'));$lastFuture=explode(',',$point(end($futureSeries),'balance_cents'));
$areaPoints=$firstFuture[0].','.($top+$plotH).' '.$balancePoints.' '.$lastFuture[0].','.($top+$plotH);
$labels=$complete?array_merge([$historySeries[0],end($historySeries)],$futureSeries):$futureSeries;
$interestShare=(float)$result['interest_share_percent'];$startValue=(int)$history[0]['valor_centavos'];$historicChange=(int)$projection['valor_inicial_centavos']-$startValue;
?>
<a class="back-link" href="<?=H::escape($basePath.'/projecoes')?>">← Todas as projeções</a>
<div class="page-heading"><div><p class="eyebrow"><?=H::escape($projection['origem_tipo']==='investimento'?'INVESTIMENTO':'OBJETIVO')?> · <?=H::escape($projection['origem_nome'])?></p><h1><?=H::escape($projection['nome'])?></h1><p class="text-secondary">Cenário recalculado com o valor atual de <?=Money::format((int)$projection['valor_inicial_centavos'])?>.</p></div><div class="d-flex gap-2"><a class="btn btn-outline-secondary" href="<?=H::escape($basePath.'/projecoes/'.$projection['id'].'/editar')?>">Editar</a><form method="post" action="<?=H::escape($basePath.'/projecoes/'.$projection['id'].'/excluir')?>" onsubmit="return confirm('Excluir esta projeção?');"><?=H::fields($csrfToken)?><button class="btn btn-outline-danger">Excluir</button></form></div></div>

<nav class="projection-view-switch mb-4" aria-label="Visão da projeção"><a class="<?=$complete?'':'active'?>" href="<?=H::escape($basePath.'/projecoes/'.$projection['id'])?>">A partir de hoje</a><a class="<?=$complete?'active':''?>" href="<?=H::escape($basePath.'/projecoes/'.$projection['id'].'?visao=completa')?>">Jornada completa</a></nav>
<?php if(!(int)$projection['origem_ativa']):?><div class="alert alert-warning">A origem desta projeção está arquivada. O cálculo continua disponível com o último valor informado.</div><?php endif;?>

<?php if($complete):?><section class="journey-summary mb-4"><div><span>Início registrado</span><strong><?=Money::format($startValue)?></strong><small><?=$dateLabel($startDate)?></small></div><div class="journey-arrow">→</div><div><span>Posição atual</span><strong><?=Money::format((int)$projection['valor_inicial_centavos'])?></strong><small class="<?=$historicChange<0?'text-danger':'text-success'?>"><?=$historicChange>=0?'+ ':''?><?=Money::format($historicChange)?></small></div><div class="journey-arrow">→</div><div><span>Objetivo final</span><strong><?=Money::format((int)$result['target_cents'])?></strong><small>estimado para <?=$month($result['estimated_month'])?></small></div></section><?php endif;?>

<div class="row g-3 mb-4">
 <div class="col-md-6 col-xl-3"><section class="card metric-card featured"><div class="card-body"><p>Prazo restante</p><strong class="metric-value"><?=$duration((int)$result['months'])?></strong><small>Meta em <?=$month($result['estimated_month'])?></small></div></section></div>
 <div class="col-md-6 col-xl-3"><section class="card metric-card"><div class="card-body"><p>Patrimônio-alvo</p><strong class="metric-value"><?=Money::format((int)$result['target_cents'])?></strong><small><?=number_format((float)$result['current_progress_percent'],1,',','.')?>% já construído</small></div></section></div>
 <div class="col-md-6 col-xl-3"><section class="card metric-card"><div class="card-body"><p>Total ao fim do cenário</p><strong class="metric-value"><?=Money::format((int)$result['total_contributed_cents'])?></strong><small>Atual + <?=Money::format((int)$result['future_contributions_cents'])?> em novos aportes</small></div></section></div>
 <div class="col-md-6 col-xl-3"><section class="card metric-card"><div class="card-body"><p>Rendimento futuro</p><strong class="metric-value text-success"><?=Money::format((int)$result['interest_cents'])?></strong><small><?=number_format($interestShare,1,',','.')?>% do patrimônio final</small></div></section></div>
</div>

<section class="card mb-4"><div class="card-body"><div class="section-heading"><div><h2 class="h4"><?=$complete?'Jornada completa do patrimônio':'Evolução futura do patrimônio'?></h2><p class="small text-secondary mb-0"><?=$complete?'Do primeiro registro, passando pela posição atual, até a meta.':'Saldo projetado comparado ao capital colocado por você.'?></p></div><div class="projection-legend"><?php if($complete):?><span><i class="history"></i>Histórico registrado</span><span><i class="current"></i>Você está aqui</span><?php endif;?><span><i class="balance"></i>Projeção</span><span><i class="contributed"></i>Aportes futuros</span></div></div>
 <div class="projection-chart-wrap"><svg class="projection-chart" viewBox="0 0 <?=$chartW?> <?=$chartH?>" role="img"><title>Evolução do patrimônio</title><desc>Histórico registrado e projeção até <?=$month($result['estimated_month'])?>.</desc>
 <?php foreach([0,25,50,75,100] as $pct):$y=$top+(1-$pct/100)*$plotH;$value=(int)round($maxValue*$pct/100);?><line x1="<?=$left?>" y1="<?=$y?>" x2="<?=$left+$plotW?>" y2="<?=$y?>" class="chart-grid"/><text x="<?=$left-10?>" y="<?=$y+4?>" text-anchor="end" class="chart-label"><?=H::escape($pct===0?'R$ 0':Money::format($value))?></text><?php endforeach;?>
 <polygon points="<?=$areaPoints?>" class="chart-area"/><?php if($complete):?><polyline points="<?=$historyPoints?>" class="chart-line history"/><?php endif;?><polyline points="<?=$contributionPoints?>" class="chart-line contributed"/><polyline points="<?=$balancePoints?>" class="chart-line balance"/>
 <?php if($complete):?><circle cx="<?=$firstFuture[0]?>" cy="<?=$firstFuture[1]?>" r="8" class="current-halo"/><circle cx="<?=$firstFuture[0]?>" cy="<?=$firstFuture[1]?>" r="4" class="current-point"/><text x="<?=$firstFuture[0]?>" y="<?=((float)$firstFuture[1]-15)?>" text-anchor="middle" class="current-label">Você está aqui</text><?php endif;?>
 <?php $shown=[];foreach($labels as $index=>$row):$key=$row['month'];if(isset($shown[$key]))continue;if($index!==0&&$index!==count($labels)-1&&$index%max(1,(int)ceil(count($labels)/6))!==0)continue;$shown[$key]=true;$x=$left+((int)$row['months']/$maxMonth)*$plotW;?><text x="<?=$x?>" y="<?=$top+$plotH+28?>" text-anchor="middle" class="chart-label"><?=$month($row['month'])?></text><?php endforeach;?>
 </svg></div>
</div></section>

<?php if($complete):?><section class="card mb-4"><div class="card-body"><details><summary class="h4 mb-0">Histórico de valores registrados</summary><div class="table-responsive mt-3"><table class="table"><thead><tr><th>Data</th><th class="text-end">Valor registrado</th><th class="text-end">Mudança</th></tr></thead><tbody><?php $previous=null;foreach($history as $row):$change=$previous===null?null:(int)$row['valor_centavos']-$previous;?><tr><td><?=$dateLabel($row['data_referencia'])?></td><td class="text-end"><strong><?=Money::format((int)$row['valor_centavos'])?></strong></td><td class="text-end <?=$change!==null&&$change<0?'text-danger':'text-success'?>"><?=$change===null?'—':(($change>=0?'+ ':'').Money::format($change))?></td></tr><?php $previous=(int)$row['valor_centavos'];endforeach;?></tbody></table></div></details></div></section><?php endif;?>

<div class="row g-4 mb-4"><div class="col-xl-7"><section class="card h-100"><div class="card-body"><h2 class="h4">Leitura do cenário</h2><div class="projection-insights"><div><span>Aporte mensal</span><strong><?=Money::format((int)$projection['aporte_mensal_centavos'])?></strong></div><div><span>Taxa informada</span><strong><?=number_format((int)$projection['taxa_quatro_casas']/10000,4,',','.')?>% ao <?=H::escape($projection['periodicidade_taxa']==='mensal'?'mês':'ano')?></strong></div><div><span>Equivalente mensal</span><strong><?=number_format((float)$result['monthly_rate_percent'],4,',','.')?>%</strong></div><div><span>Equivalente anual</span><strong><?=number_format((float)$result['annual_rate_percent'],2,',','.')?>%</strong></div><?php if($result['months_without_interest']!==null):?><div><span>Prazo sem rendimento</span><strong><?=$duration((int)$result['months_without_interest'])?></strong></div><div><span>Tempo potencialmente reduzido</span><strong><?=((int)$result['months_saved']===0?'0 meses':$duration((int)$result['months_saved']))?></strong></div><?php endif;?></div></div></section></div><div class="col-xl-5"><section class="card h-100"><div class="card-body"><h2 class="h4">Marcos restantes</h2><?php foreach($result['milestones'] as $milestone):?><div class="projection-milestone"><span><strong><?=$milestone['percentage']?>%</strong><small><?=$duration((int)$milestone['months'])?></small></span><span class="text-end"><strong><?=$month($milestone['month'])?></strong><small><?=Money::format((int)$milestone['balance_cents'])?></small></span></div><?php endforeach;?></div></section></div></div>

<section class="card"><div class="card-body"><details><summary class="h4 mb-0">Tabela anual da projeção futura</summary><div class="table-responsive mt-3"><table class="table projection-table"><thead><tr><th>Período</th><th>Tempo restante</th><th class="text-end">Capital acumulado</th><th class="text-end">Rendimentos futuros</th><th class="text-end">Patrimônio</th><th class="text-end">Meta</th></tr></thead><tbody><?php foreach($series as $row):?><tr><td><?=$month($row['month'])?></td><td><?=$duration((int)$row['months'])?></td><td class="text-end"><?=Money::format((int)$row['contributed_cents'])?></td><td class="text-end text-success"><?=Money::format((int)$row['interest_cents'])?></td><td class="text-end"><strong><?=Money::format((int)$row['balance_cents'])?></strong></td><td class="text-end"><?=number_format(min(100,(int)$row['balance_cents']/(int)$result['target_cents']*100),1,',','.')?>%</td></tr><?php endforeach;?></tbody></table></div></details><p class="small text-secondary mt-3 mb-0">O histórico contém os valores efetivamente registrados no UaiMoney; entre atualizações, o sistema não inventa rentabilidade. A parte futura é uma projeção matemática com taxa constante e aportes no fim do mês, sem inflação, impostos ou custos.</p></div></section>
